---
title: "Modelos con moderadores"
format: html

execute: 
  echo: false
  warning: false
---

```{r}

source(here::here("script/proc_data.R"))

# Convertimos las variables de control a factores
data <- data %>%
  mutate(across(c(
    # Variables SAE
    disclosure, inf_situacional, control_humano,
    # Variables FONASA
    ai_disclosure_fonasa, control_humano_fonasa, performance_fonasa
  ), as.factor))

data <- data%>%
  filter(eliminado == 0)

library(sjPlot)

data <- data %>%
  mutate(
    attitudes_tech = rowMeans(
      select(., starts_with("pre_general_attitudes_tech")),
      na.rm = TRUE),
    alfabetizacion_digital = rowMeans(
      select(., starts_with("alfabetizacion_digital")),
      na.rm = TRUE),  
    ai_skills = rowMeans(
      select(., starts_with("ai_skills")),
      na.rm = TRUE), 
    attitudes_ai = rowMeans(
      select(., starts_with("general_attitudes_ai")),
      na.rm = TRUE),
    get_variable_ord_sae = ifelse(get_variable_ord == 1, "Fonasa", "SAE"),
    uso_sae = rowMeans(
      select(., starts_with("sae_familiaridad_uso")),
      na.rm = TRUE),
    sae_familiaridad_recode = ifelse(sae_familiaridad_3 == "No sé.", "No.", sae_familiaridad_3)
    )

```

# Correlación moderadores

```{r}
library(ggcorrplot)
library(rstatix)
# Seleccionamos las columnas en el orden exacto deseado
moderators <- data %>%
  select(
    ai_skills,attitudes_ai,attitudes_tech,alfabetizacion_digital, get_variable_ord,
    device_type)%>%
  mutate(
    device_type = ifelse(device_type == "desktop",1,0)
  )# Esto quita "sae_" de todos los nombres

# Calculamos correlación
moderators <- moderators %>%
  rename(
    attitudes_mcknight = attitudes_tech,
    hargittai_literacy = alfabetizacion_digital
  )
p_mat_moderators <- cor_pmat(moderators)
moderators_corr <- cor(moderators, use = "complete.obs")

# 3. Graficar filtrando por significancia (p < 0.05)
ggcorrplot(moderators_corr, 
           hc.order = FALSE,
           type = "upper",
           lab = TRUE,
           lab_size = 2.5,
           sig.level = 0.05,       # Nivel de significancia (0.05 para 95% confianza)
           insig = "blank",        # "blank" deja vacío lo que NO es significativo
           colors = c("#E46726", "white", "#6D9EC1"),
           title = "Correlaciones Significativas")
```

# Main moderators

## FONASA

### Ex Ante Human control

```{r}
tab_model(list(
lm(fonasa_comp_objetiva_pre ~ control_humano_fonasa*ai_skills + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pre ~ control_humano_fonasa*ai_skills + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pre ~ control_humano_fonasa*ai_skills + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pre ~ control_humano_fonasa*ai_skills + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pre ~ control_humano_fonasa*ai_skills + 
     genero + edad_num + education_recoded, data = data)),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_comp_objetiva_pre ~ control_humano_fonasa*attitudes_ai + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pre ~ control_humano_fonasa*attitudes_ai + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pre ~ control_humano_fonasa*attitudes_ai + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pre ~ control_humano_fonasa*attitudes_ai + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pre ~ control_humano_fonasa*attitudes_ai + 
     genero + edad_num + education_recoded, data = data)),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```


### AI SKILLS

```{r}
tab_model(list(
lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa*ai_skills + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa*ai_skills + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa*ai_skills + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa*ai_skills + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
#  pred.labels = c("Intercept", "Human control (Ex-pos)","Performance (Ex-pos)", "AI disclosure (Ex-ante)", #"Género: Mujer", "Edad", "Educación: Media completa", "Educación: Superior"),
 # dv.labels = c("Objective knowledge (Ex-pos)", "Subjective knowledge (Ex-pos)", "Moral trust MDMT (Ex-pos)", #"Moral trust McKnight (Ex-pos)", "Functional trust MDMT (Ex-pos)", "Functional trust McKnight (Ex-pos)") 
)
```


```{r}
tab_model(list(
lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa*ai_skills + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa*ai_skills + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
#  pred.labels = c("Intercept", "Human control (Ex-pos)","Performance (Ex-pos)", "AI disclosure (Ex-ante)", #"Género: Mujer", "Edad", "Educación: Media completa", "Educación: Superior"),
 # dv.labels = c("Objective knowledge (Ex-pos)", "Subjective knowledge (Ex-pos)", "Moral trust MDMT (Ex-pos)", #"Moral trust McKnight (Ex-pos)", "Functional trust MDMT (Ex-pos)", "Functional trust McKnight (Ex-pos)") 
)
```

```{r}
tab_model(list(
lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa*ai_skills + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa*ai_skills + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
#  pred.labels = c("Intercept", "Human control (Ex-pos)","Performance (Ex-pos)", "AI disclosure (Ex-ante)", #"Género: Mujer", "Edad", "Educación: Media completa", "Educación: Superior"),
 # dv.labels = c("Objective knowledge (Ex-pos)", "Subjective knowledge (Ex-pos)", "Moral trust MDMT (Ex-pos)", #"Moral trust McKnight (Ex-pos)", "Functional trust MDMT (Ex-pos)", "Functional trust McKnight (Ex-pos)") 
)
```

```{r}
tab_model(list(
lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa*ai_skills + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa*ai_skills + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
#  pred.labels = c("Intercept", "Human control (Ex-pos)","Performance (Ex-pos)", "AI disclosure (Ex-ante)", #"Género: Mujer", "Edad", "Educación: Media completa", "Educación: Superior"),
 # dv.labels = c("Objective knowledge (Ex-pos)", "Subjective knowledge (Ex-pos)", "Moral trust MDMT (Ex-pos)", #"Moral trust McKnight (Ex-pos)", "Functional trust MDMT (Ex-pos)", "Functional trust McKnight (Ex-pos)") 
)
```

```{r}
tab_model(list(
lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa*ai_skills + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa*ai_skills + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
#  pred.labels = c("Intercept", "Human control (Ex-pos)","Performance (Ex-pos)", "AI disclosure (Ex-ante)", #"Género: Mujer", "Edad", "Educación: Media completa", "Educación: Superior"),
 # dv.labels = c("Objective knowledge (Ex-pos)", "Subjective knowledge (Ex-pos)", "Moral trust MDMT (Ex-pos)", #"Moral trust McKnight (Ex-pos)", "Functional trust MDMT (Ex-pos)", "Functional trust McKnight (Ex-pos)") 
)
```

### AI ATTITUDES

```{r}
tab_model(list(
lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa*attitudes_ai + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa*attitudes_ai + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa*attitudes_ai + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa*attitudes_ai + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa*attitudes_ai + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa*attitudes_ai + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa*attitudes_ai + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa*attitudes_ai + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa*attitudes_ai + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa*attitudes_ai + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```


```{r}
tab_model(list(
lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa*attitudes_ai + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa*attitudes_ai + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

## Device Type

```{r}
tab_model(list(
lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa*device_type + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa*device_type + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_objetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa*device_type + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa*device_type + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_comp_subjetiva_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa*device_type + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa*device_type + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa*device_type + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa*device_type + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_belief_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa*device_type + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa*device_type + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_funcional_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa + 
     genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa*device_type + performance_fonasa + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa*device_type + ai_disclosure_fonasa + genero + edad_num + education_recoded, data = data),

lm(fonasa_conf_word_moral_pos ~ control_humano_fonasa + performance_fonasa + ai_disclosure_fonasa*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

### Graficos FONASA

```{r}
library(ggeffects)

ggpredict(
  lm(
  fonasa_comp_objetiva_pos ~ 
    control_humano_fonasa +
    performance_fonasa * ai_skills +
    ai_disclosure_fonasa +
    genero +
    edad_num +
    education_recoded,
  data = data
),
  terms = c("ai_skills", "performance_fonasa")
)%>%

ggplot(aes(
         x = x,
         y = predicted,
         color = group
       )) +
  geom_line(linewidth = 1.2) +
  geom_ribbon(
    aes(ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.15,
    color = NA
  ) +
  labs(
    x = "AI skills",
    y = "Objective comprehension (FONASA, post)",
    color = "Performance intervention",
    fill  = "Performance intervention"
  ) +
  scale_color_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Performance = 0", "1" = "Performance = 1")
  ) +
  scale_fill_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Performance = 0", "1" = "Performance = 1")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top"
  )
```


```{r}
ggpredict(
  lm(
  fonasa_comp_subjetiva_pos ~ 
    control_humano_fonasa * ai_skills +
    performance_fonasa +
    ai_disclosure_fonasa +
    genero +
    edad_num +
    education_recoded,
  data = data
),
  terms = c("ai_skills", "control_humano_fonasa")
)%>%

ggplot(aes(
         x = x,
         y = predicted,
         color = group
       )) +
  geom_line(linewidth = 1.2) +
  geom_ribbon(
    aes(ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.15,
    color = NA
  ) +
  labs(
    x = "AI skills",
    y = "Subjective comprehension (FONASA, post)",
    color = "Human control",
    fill  = "Human control"
  ) +
  scale_color_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Human control = 0", "1" = "Human control = 1")
  ) +
  scale_fill_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Human control = 0", "1" = "Human control = 1")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top"
  )
```

## SAE

### Ex ante moderators

```{r}
tab_model(
  lm(sae_comp_objetiva_pre ~ inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),
   lm(sae_comp_objetiva_pre ~ inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data),
   lm(sae_comp_subjetiva_pre ~ inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),
   lm(sae_comp_subjetiva_pre ~ inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data),
   lm(sae_conf_belief_funcional_pre ~ inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),
   lm(sae_conf_belief_funcional_pre ~ inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data),
   lm(sae_conf_belief_moral_pre ~ inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),
   lm(sae_conf_belief_moral_pre ~ inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data),
   lm(sae_conf_word_funcional_pre ~ inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),  
  lm(sae_conf_word_funcional_pre ~ inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data),  
  lm(sae_conf_word_moral_pre ~ inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),
  lm(sae_conf_word_moral_pre ~ inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)

```

### AI SKILLS
```{r}
tab_model(list(
lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pos ~ control_humano*ai_skills + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano*ai_skills + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano*ai_skills + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano*ai_skills + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano*ai_skills + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano*ai_skills + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure*ai_skills + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

### AI ATTITUDES

```{r}
tab_model(list(
lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pos ~ control_humano*attitudes_ai + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional*attitudes_ai + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional + disclosure*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano*attitudes_ai + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional*attitudes_ai + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional + disclosure*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```



```{r}
tab_model(list(
lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano*attitudes_ai + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional*attitudes_ai + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano*attitudes_ai + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional*attitudes_ai + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano*attitudes_ai + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional*attitudes_ai + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano*attitudes_ai + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional*attitudes_ai + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure*attitudes_ai + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```


### Device type

```{r}
tab_model(list(
lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pos ~ control_humano*device_type + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional*device_type + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional + disclosure*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano*device_type + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional*device_type + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pos ~ control_humano + inf_situacional + disclosure*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```



```{r}
tab_model(list(
lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano*device_type + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional*device_type + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano*device_type + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional*device_type + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano*device_type + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional*device_type + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano*device_type + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional*device_type + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure*device_type + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

### Use SAE

```{r}
tab_model(list(
lm(sae_comp_objetiva_pre ~ inf_situacional + disclosure, data = data),

lm(sae_comp_objetiva_pre ~ inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pre ~ inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pre ~ inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_comp_subjetiva_pre ~ inf_situacional + disclosure, data = data),

lm(sae_comp_subjetiva_pre ~ inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pre ~ inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pre ~ inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_belief_funcional_pre ~ inf_situacional + disclosure, data = data),

lm(sae_conf_belief_funcional_pre ~ inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pre ~ inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pre ~ inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pre ~ inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_belief_moral_pre ~ inf_situacional + disclosure, data = data),

lm(sae_conf_belief_moral_pre ~ inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pre ~ inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pre ~ inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pre ~ inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```



```{r}
tab_model(list(
lm(sae_conf_word_funcional_pre ~ inf_situacional + disclosure, data = data),

lm(sae_conf_word_funcional_pre ~ inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pre ~ inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pre ~ inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pre ~ inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_word_moral_pre ~ inf_situacional + disclosure, data = data),

lm(sae_conf_word_moral_pre ~ inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pre ~ inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pre ~ inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pre ~ inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_comp_objetiva_pre ~ inf_situacional + disclosure, data = data),

lm(sae_comp_objetiva_pre ~ inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pre ~ inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_objetiva_pre ~ inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_comp_subjetiva_pre ~ inf_situacional + disclosure, data = data),

lm(sae_comp_subjetiva_pre ~ inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pre ~ inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_comp_subjetiva_pre ~ inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano*uso_sae + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano*uso_sae + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano*uso_sae + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_funcional_pos ~ control_humano + inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```

```{r}
tab_model(list(
lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure + 
     genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano*uso_sae + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional*uso_sae + disclosure + genero + edad_num + education_recoded, data = data),

lm(sae_conf_word_moral_pos ~ control_humano + inf_situacional + disclosure*uso_sae + genero + edad_num + education_recoded, data = data)
),
  collapse.se = TRUE,      
  show.ci = FALSE,
  show.aic = FALSE,
  show.r2 = TRUE,
  show.fstat = TRUE,
  p.style = "stars"
)
```



### Gráficos SAE

```{r}
ggpredict(
lm(sae_comp_objetiva_pos ~ control_humano + inf_situacional*ai_skills + disclosure + genero + edad_num + education_recoded, data = data),
  terms = c("ai_skills", "inf_situacional")
)%>%

ggplot(aes(
         x = x,
         y = predicted,
         color = group
       )) +
  geom_line(linewidth = 1.2) +
  geom_ribbon(
    aes(ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.15,
    color = NA
  ) +
  labs(
    x = "AI skills",
    y = "Objective comprehension (SAE, post)",
    color = "Situational information",
    fill  = "Situational information"
  ) +
  scale_color_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Situational information = 0", "1" = "Situational information = 1")
  ) +
  scale_fill_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Situational information = 0", "1" = "Situational information = 1")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top"
  )
```

```{r}
ggpredict(
lm(sae_comp_objetiva_pos ~ control_humano*attitudes_ai + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),
  terms = c("attitudes_ai", "control_humano")
)%>%

ggplot(aes(
         x = x,
         y = predicted,
         color = group
       )) +
  geom_line(linewidth = 1.2) +
  geom_ribbon(
    aes(ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.15,
    color = NA
  ) +
  labs(
    x = "AI attitudes",
    y = "Objective comprehension (SAE, post)",
    color = "Human Control",
    fill  = "Human Control"
  ) +
  scale_color_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Human Control = 0", "1" = "Human Control = 1")
  ) +
  scale_fill_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Human Control = 0", "1" = "Human Control = 1")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top"
  )
```

```{r}
ggpredict(
lm(sae_comp_subjetiva_pos ~ control_humano*attitudes_ai + inf_situacional + disclosure + genero + edad_num + education_recoded, data = data),
  terms = c("attitudes_ai", "control_humano")
)%>%

ggplot(aes(
         x = x,
         y = predicted,
         color = group
       )) +
  geom_line(linewidth = 1.2) +
  geom_ribbon(
    aes(ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.15,
    color = NA
  ) +
  labs(
    x = "AI attitudes",
    y = "Subjective comprehension (SAE, post)",
    color = "Human Control",
    fill  = "Human Control"
  ) +
  scale_color_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Human Control = 0", "1" = "Human Control = 1")
  ) +
  scale_fill_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Human Control = 0", "1" = "Human Control = 1")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top"
  )
```


```{r}
ggpredict(
lm(sae_conf_belief_funcional_pos ~ control_humano + inf_situacional*attitudes_ai + disclosure + genero + edad_num + education_recoded, data = data),
  terms = c("attitudes_ai", "inf_situacional")
)%>%

ggplot(aes(
         x = x,
         y = predicted,
         color = group
       )) +
  geom_line(linewidth = 1.2) +
  geom_ribbon(
    aes(ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.15,
    color = NA
  ) +
  labs(
    x = "AI attitudes",
    y = "Functional trust belief (SAE, post)",
    color = "Situational information",
    fill  = "Situational information"
  ) +
  scale_color_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Situational information = 0", "1" = "Situational information = 1")
  ) +
  scale_fill_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Situational information = 0", "1" = "Situational information = 1")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top"
  )
```

```{r}
ggpredict(
lm(sae_conf_belief_moral_pos ~ control_humano + inf_situacional*attitudes_ai + disclosure + genero + edad_num + education_recoded, data = data),
  terms = c("attitudes_ai", "inf_situacional")
)%>%

ggplot(aes(
         x = x,
         y = predicted,
         color = group
       )) +
  geom_line(linewidth = 1.2) +
  geom_ribbon(
    aes(ymin = conf.low, ymax = conf.high, fill = group),
    alpha = 0.15,
    color = NA
  ) +
  labs(
    x = "AI attitudes",
    y = "Moral trust belief (SAE, post)",
    color = "Situational information",
    fill  = "Situational information"
  ) +
  scale_color_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Situational information = 0", "1" = "Situational information = 1")
  ) +
  scale_fill_manual(
    values = c("0" = "#1B9E77", "1" = "#D95F02"),
    labels = c("0" = "Situational information = 0", "1" = "Situational information = 1")
  ) +
  theme_minimal(base_size = 13) +
  theme(
    legend.position = "top"
  )
```

```{r}
data <- data %>%
  mutate(
    device_type = factor(
      device_type,
      levels = c("desktop", "mobile")  # referencia clara
    ),
    control_humano = factor(
      control_humano,
      levels = c(0, 1)
    )
  )

library(ggeffects)
library(ggplot2)

m_device_control <- lm(
  sae_comp_objetiva_pos ~ 
    control_humano * device_type +
    inf_situacional +
    disclosure +
    genero +
    edad_num +
    education_recoded,
  data = data
)

plot_model(m_device_control, terms = c("control_humano", "device_type"), type = "int")

```

```{r}
plot_model(lm(
  sae_comp_subjetiva_pos ~ 
    control_humano * device_type +
    inf_situacional +
    disclosure +
    genero +
    edad_num +
    education_recoded,
  data = data
), terms = c("control_humano", "device_type"), type = "int")

```


```{r}
plot_model(lm(
  sae_conf_belief_funcional_pos ~ 
    control_humano * device_type +
    inf_situacional +
    disclosure +
    genero +
    edad_num +
    education_recoded,
  data = data
), terms = c("control_humano", "device_type"), type = "int")

```

```{r}
plot_model(lm(
  sae_conf_belief_moral_pos ~ 
    control_humano * device_type +
    inf_situacional +
    disclosure +
    genero +
    edad_num +
    education_recoded,
  data = data
), terms = c("control_humano", "device_type"), type = "int")
```

```{r}
plot_model(lm(
  sae_conf_word_funcional_pos ~ 
    control_humano * device_type +
    inf_situacional +
    disclosure +
    genero +
    edad_num +
    education_recoded,
  data = data
), terms = c("control_humano", "device_type"), type = "int")
```

```{r}
plot_model(lm(
  sae_conf_belief_moral_pos ~ 
    control_humano * device_type +
    inf_situacional +
    disclosure +
    genero +
    edad_num +
    education_recoded,
  data = data
), terms = c("control_humano", "device_type"), type = "int")
```


